### ISSUE TITLE
TypeError: $iterator(...) is not a function

### ISSUE THREAD

**Issue by tsmithf** [ngrebenshikov/openfl-alivepdf#5]
Trying to use openfl-alivePDF doesn't seem to work using the example supplied, it compiles, but when it runs the browser console reports an error in the code...

TypeError: $iterator(...) is not a function, which occurs at var _ = $iterator(it)(); in the following code....

Lambda.count = function(it,pred) {
	var n = 0;
	if(pred == null) {
		var _ = $iterator(it)();
		while(_.hasNext()) {
			var _1 = _.next();
			++n;
		}
	} else {
		var x = $iterator(it)();
		while(x.hasNext()) {
			var x1 = x.next();
			if(pred(x1)) {
				++n;
			}
		}
	}

**Comment by ngrebenshikov** [comment]
It seams it's a haxe toolkit related issue. What versions of haxe compiler, lime and OpenFL are used?

**Comment by tsmithf** [comment]
Thanks for the fast response.

This is my current haxelib list...

actuate: 1.8.6 1.8.7 [1.8.9]
away3d-samples: 5.0.2 [5.0.3]
away3d: 5.0.6 5.0.7 [5.0.8]
box2d: [1.2.3]
format: 3.3.0 3.4.0 3.4.1 [3.4.2]
gm2d: 3.3.4 3.3.24 3.3.54 [4.0.22]
haxe-crypto: [0.0.7]
haxe-gif: [0.3.3]
haxe-strings: 5.0.0 5.0.1 5.1.0 [5.2.2]
haxeui: [1.8.21]
hscript: 2.0.7 2.1.1 2.2.0 [2.3.0]
hvm: [0.0.2]
hxcpp-debugger: [1.0.6]
hxcpp: 3.2.205 3.4.64 3.4.188 4.0.4 [4.0.8]
hxp: 1.1.0 [1.1.2]
hxsocketio: [0.1.0]
hxtelemetry: [0.3.5]
hxtools: [1.1.6]
hxWebSockets: [1.1.1]
layout: [1.2.1]
lime-samples: 2.6.0 4.0.1 6.2.0 [7.0.0]
lime-tools: [1.5.7]
lime: 2.8.3 2.9.1 4.0.3 5.3.0 5.6.0 5.7.1 6.0.1 6.2.0 6.3.1 6.4.0 7.0.0 7.1.0 7.1.1 7.2.1 [7.3.0]
nme: 5.5.7 5.7.1 [6.0.58]
node-webkit: [1.0.7]
openfl-alivepdf: [git]
openfl-html5-dom: [1.2.2]
openfl-html5: 1.0.5 [1.4.2-beta]
openfl-native: [1.4.0]
openfl-samples: 3.3.1 4.9.0 6.0.0 8.4.0 [8.7.0]
openfl-tools: [1.0.10]
openfl-webm: [0.0.4]
openfl: 3.5.3 3.6.1 4.9.2 6.0.1 6.2.0 6.2.2 7.0.0 7.1.2 8.0.2 8.1.1 8.2.2 8.3.0 8.4.0 8.4.1 8.5.1 8.6.0 8.6.2 8.6.4 8.7.0 8.8.0 [8.9.0]
stablexui: [1.2.2]
svg: 1.0.8 1.1.1 [1.1.2]
swf: 2.1.6 [2.3.1]
tweenxcore: 1.0.3 [1.0.4]
vectorasset: [1.1.0]
yagp: [1.1.4]
zame-particles: 1.0.2 1.0.3 1.0.4 1.0.5 [1.1.0]
zip: [1.1.0]

And Haxe 3.4.7

**Comment by ngrebenshikov** [comment]
Hm. Looks good.
What other libs (except openfl-alivepdf) are used in the project? Could you show your code where alivepdf is used?

**Comment by tsmithf** [comment]
As a test I used the example in the repository, and the error occurs in that too.

I tried -Dwebgl, -Dcanvas & -Ddom and the error occurs under all of them

**Comment by ngrebenshikov** [comment]
OK. I'll try to reproduce.

**Comment by ngrebenshikov** [comment]
@tsmithf thank you for raising an issue. I've just committed the fix.
